import os
from os import getenv
from dotenv import load_dotenv
TIME_LIMIT = int(getenv("TIME_LIMIT", "2592000"))
TIME_SLEEP = int(getenv("TIME_SLEEP", "86400"))

load_dotenv(".env")
load_dotenv(".env1")


API_ID = int(getenv("API_ID", "1634450")) #optional
API_HASH = getenv("API_HASH", "1a42e816cae8d86e71a4c466bba19b8c") #optional
SUDO_USERS = list(map(int, getenv("SUDO_USERS", "").split()))
DEEP_AI = getenv("DEEP_AI", "d7394561-0528-4714-a1ee-edd7020b48e1")
OWNER_ID = int(getenv("OWNER_ID") or 0)
ADMIN1_ID = list(map(int, getenv("ADMIN1_ID").split()))
ADMIN2_ID = list(map(int, getenv("ADMIN2_ID").split()))
ADMIN3_ID = list(map(int, getenv("ADMIN3_ID").split()))
ADMIN4_ID = list(map(int, getenv("ADMIN4_ID").split()))
ADMIN5_ID = list(map(int, getenv("ADMIN5_ID").split()))
ADMIN6_ID = list(map(int, getenv("ADMIN6_ID").split()))
ADMIN7_ID = list(map(int, getenv("ADMIN7_ID").split()))

MONGO_URL = getenv("MONGO_URL")
BOT_TOKEN = getenv("BOT_TOKEN")
ALIVE_PIC = getenv("ALIVE_PIC")
ALIVE_TEXT = getenv("ALIVE_TEXT")
PM_LOGGER = getenv("PM_LOGGER", True)
OPENAI_API_KEY = getenv("OPENAI_API_KEY")
BOTLOG_CHATID = int(getenv("BOTLOG_CHATID") or 0)
BLACKLIST_GCAST = {int(x) for x in getenv("BLACKLIST_GCAST", "").split()}
GIT_TOKEN = getenv("GIT_TOKEN") #personal access token
REPO_URL = getenv("REPO_URL" or None)
HEROKU_API_KEY = getenv("HEROKU_API_KEY")
HEROKU_APP_NAME = getenv("HEROKU_APP_NAME")
BRANCH = getenv("BRANCH", "main") #don't change
CMD_HNDLR = getenv("CMD_HNDLR", ".")
SUPPORT = int(getenv("SUPPORT"))
CHANNEL = int(getenv("CHANNEL"))
SESSION1 = getenv("SESSION1", "")
SESSION2 = getenv("SESSION2", "")
SESSION3 = getenv("SESSION3", "")
SESSION4 = getenv("SESSION4", "")
SESSION5 = getenv("SESSION5", "")
SESSION6 = getenv("SESSION6", "")
SESSION7 = getenv("SESSION7", "")
SESSION8 = getenv("SESSION8", "")
SESSION9 = getenv("SESSION9", "")
SESSION10 = getenv("SESSION10", "")
SESSION11 = getenv("SESSION11", "")
SESSION12 = getenv("SESSION12", "")
SESSION13 = getenv("SESSION13", "")
SESSION14 = getenv("SESSION14", "")
SESSION15 = getenv("SESSION15", "")
SESSION16 = getenv("SESSION16", "")
SESSION17 = getenv("SESSION17", "")
SESSION18 = getenv("SESSION18", "")
SESSION19 = getenv("SESSION19", "")
SESSION20 = getenv("SESSION20", "")
SESSION21 = getenv("SESSION21", "")
SESSION22 = getenv("SESSION22", "")
SESSION23 = getenv("SESSION23", "")
SESSION24 = getenv("SESSION24", "")
SESSION25 = getenv("SESSION25", "")
SESSION26 = getenv("SESSION26", "")
SESSION27 = getenv("SESSION27", "")
SESSION28 = getenv("SESSION28", "")
SESSION29 = getenv("SESSION29", "")
SESSION30 = getenv("SESSION30", "")
SESSION31 = getenv("SESSION31", "")
SESSION32 = getenv("SESSION32", "")
SESSION33 = getenv("SESSION33", "")
SESSION34 = getenv("SESSION34", "")
SESSION35 = getenv("SESSION35", "")
SESSION36 = getenv("SESSION36", "")
SESSION37 = getenv("SESSION37", "")
SESSION38 = getenv("SESSION38", "")
SESSION39 = getenv("SESSION39", "")
SESSION40 = getenv("SESSION40", "")
SESSION41 = getenv("SESSION41", "")
SESSION42 = getenv("SESSION42", "")
SESSION43 = getenv("SESSION43", "")
SESSION44 = getenv("SESSION44", "")
SESSION45 = getenv("SESSION45", "")
SESSION46 = getenv("SESSION46", "")
SESSION47 = getenv("SESSION47", "")
SESSION48 = getenv("SESSION48", "")
SESSION49 = getenv("SESSION49", "")
SESSION50 = getenv("SESSION50", "")

